BEGIN TRANSACTION;
CREATE TABLE  WiringDiagram (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	OpenTime	BIGINT NOT NULL,
	Duration	INTEGER NOT NULL
);
CREATE TABLE  UtilTools (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	Type	TEXT NOT NULL,
	Time	BIGINT NOT NULL
);
CREATE TABLE  UploadClick (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	Time	BIGINT NOT NULL
);
CREATE TABLE  Tutorial (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	isClick	INTEGER NOT NULL,
	Page	INTEGER NOT NULL,
	OpenTime	BIGINT NOT NULL,
	Duration	INTEGER NOT NULL
);
CREATE TABLE  Launching (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	OpenTime	BIGINT NOT NULL,
	Duration	INTEGER NOT NULL
);
CREATE TABLE  Graph (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	FileID	TEXT NOT NULL,
	Time	BIGINT NOT NULL
);
CREATE TABLE  Error (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	Time	BIGINT NOT NULL,
	Message	TEXT NOT NULL
);
CREATE TABLE  EditSceneName (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	ObjectID	TEXT NOT NULL,
	NewName	TEXT NOT NULL
);
CREATE TABLE  CopyCode (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	Time	BIGINT NOT NULL
);
CREATE TABLE  ConfigDevice (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	ObjectID	TEXT NOT NULL,
	RealHW	TEXT NOT NULL,
	isAuto	INTEGER NOT NULL,
	Port	TEXT,
	Time	BIGINT NOT NULL
);
CREATE TABLE  ClickorDragBeginButton (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	Action	TEXT NOT NULL,
	Time	BIGINT NOT NULL
);
CREATE TABLE  ClickURL (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	Time	BIGINT NOT NULL,
	URL	TEXT NOT NULL
);
CREATE TABLE  ChangeDeviceName (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	ObjectID	TEXT NOT NULL,
	newName	TEXT NOT NULL,
	Time	BIGINT NOT NULL
);
CREATE TABLE  Canvas (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	HowtoDrag	TEXT NOT NULL,
	Time	BIGINT NOT NULL
);
CREATE TABLE  AddorDelDevice (
	ID	INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	App_ID	TEXT NOT NULL,
	Action	TEXT NOT NULL,
	Object_ID	TEXT NOT NULL,
	Type	TEXT NOT NULL,
	Time	BIGINT NOT NULL
);
COMMIT;
